linters-settings:
  container:
    exclude-rules:
      liveness-probe:
        - kind: Deployment
          name: snapshot-validation-webhook
          container: snapshot-validation
      readiness-probe:
        - kind: Deployment
          name: snapshot-validation-webhook
          container: snapshot-validation
