linters-settings:
  container:
    exclude-rules:
      liveness-probe:
        - kind: Deployment
          name: snapshot-controller
          container: snapshot-controller
      readiness-probe:
        - kind: Deployment
          name: snapshot-controller
          container: snapshot-controller
  no-cyrillic:
    exclude-rules:
      directories:
        - hack/
