---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhooks
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:webhooks
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
rules:
  - apiGroups:
      - storage.k8s.io
    verbs:
      - get
      - list
    resources:
      - storageclasses
  - apiGroups:
      - core.k8s.io
    verbs:
      - get
      - list
    resources:
      - persistentvolumeclaims
  - apiGroups:
      - snapshot.storage.k8s.io
    verbs:
      - get
      - list
    resources:
      - volumesnapshotclasses

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:webhooks
  {{- include "helm_lib_module_labels" (list . (dict "app" "webhooks")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:webhooks
subjects:
  - kind: ServiceAccount
    name: webhooks
    namespace: d8-{{ .Chart.Name }}
